# Generated by Django 2.2.10 on 2020-06-25 13:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JR_SERVICE_USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_ID', models.IntegerField()),
                ('SERVICE_DESC', models.CharField(max_length=255)),
                ('SERVICE_REQ_FOR', models.CharField(max_length=10)),
                ('SERVICE_USER_LOC', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('SERVICE_DATE_TIME', models.DateTimeField(auto_now_add=True)),
                ('SERVICE_STATUS', models.BooleanField(default=False)),
                ('USER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VOLUNTEER_LOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VOLUNTEER_CURR_LOC', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('VOLUNTEER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_VOLUNTEER_DND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DND_FL', models.BooleanField(default=False)),
                ('VOLUNTEER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_VOLUNTEER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VOLUNTEER_LEVEL_ID', models.CharField(max_length=22)),
                ('VOLUNTEER_NAME', models.CharField(max_length=100)),
                ('VOLUNTEER_TITLE', models.CharField(max_length=100)),
                ('VOLUNTEER_EMAIL', models.CharField(max_length=100)),
                ('VOLUNTEER_GENDER', models.CharField(max_length=1)),
                ('VOLUNTEER_DOB', models.DateField(max_length=8)),
                ('VOLUNTEER_ADDR', models.CharField(blank=True, max_length=255)),
                ('VOLUNTEER_CITY', models.CharField(blank=True, max_length=255)),
                ('VOLUNTEER_STATE', models.CharField(blank=True, max_length=255)),
                ('VOLUNTEER_COUNTRY', models.CharField(blank=True, max_length=255)),
                ('VOLUNTEER_PINCODE', models.CharField(blank=True, max_length=255)),
                ('VOLUNTEER_SPECIALITY', models.CharField(blank=True, max_length=100)),
                ('VOLUNTEER_IS_CERTIFIED', models.BooleanField(default=False)),
                ('D_CREATION_DT', models.DateTimeField(auto_now_add=True)),
                ('D_UPDATE_DT', models.DateTimeField(auto_now_add=True)),
                ('VOLUNTEER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_USER_HEALTH_HIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_HH_CONDITION_NM', models.CharField(blank=True, max_length=255)),
                ('USER_HH_ALLERGY_DESC', models.CharField(blank=True, max_length=255)),
                ('USER_HH_MED_ALLERGY_DESC', models.CharField(blank=True, max_length=255)),
                ('USER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_FIRST_NM', models.CharField(max_length=100)),
                ('USER_MIDDLE_NM', models.CharField(blank=True, max_length=100)),
                ('USER_LAST_NM', models.CharField(blank=True, max_length=100)),
                ('USER_EMAIL', models.EmailField(blank=True, max_length=100)),
                ('USER_EMERGENCY_NO', models.CharField(max_length=12)),
                ('USER_GENDER', models.CharField(max_length=1)),
                ('USER_DOB', models.DateField(max_length=8)),
                ('USER_BLOOD_GROUP', models.CharField(max_length=10)),
                ('USER_ADDR1', models.CharField(blank=True, max_length=255)),
                ('USER_ADDR2', models.CharField(blank=True, max_length=255)),
                ('USER_CITY', models.CharField(blank=True, max_length=255)),
                ('USER_STATE', models.CharField(blank=True, max_length=255)),
                ('USER_COUNTRY', models.CharField(blank=True, max_length=255)),
                ('USER_PINCODE', models.CharField(blank=True, max_length=255)),
                ('USER_IS_VOLUNTEER', models.BooleanField(default=False)),
                ('D_CREATION_DT', models.DateTimeField(auto_now_add=True)),
                ('D_UPDATE_DT', models.DateTimeField(auto_now_add=True)),
                ('USER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_SERVICE_VOLUNTEER_ACPT_RJCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_FLAG', models.BooleanField(default=False)),
                ('SERVICE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JR_SERVICE_USER')),
                ('VOLUNTEER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_SERVICE_VOLUNTEER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_DESC', models.CharField(max_length=255)),
                ('SERVICE_REQ_FOR', models.CharField(max_length=10)),
                ('SERVICE_VOLUNTEER_LOC', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('SERVICE_DATE_TIME', models.DateTimeField(auto_now_add=True)),
                ('SERVICE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JR_SERVICE_USER')),
                ('VOLUNTEER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JR_CASE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_DESC', models.CharField(blank=True, max_length=255)),
                ('CASE_DT_TM', models.DateTimeField(auto_now_add=True)),
                ('SERVICE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JR_SERVICE_USER')),
                ('USER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL)),
                ('VOLUNTEER_PH_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
